<?php
$root_id = $section_anchor ?: $section_instance;
$items = is_array( $section_data['items'] ?? null ) ? $section_data['items'] : array();
$trust = is_array( $section_data['secondary_items'] ?? null ) ? $section_data['secondary_items'] : array();
$hero_image_url = is_numeric( $section_data['image'] ?? null ) ? wp_get_attachment_image_url( (int) $section_data['image'], 'large' ) : '';
$calculator_data = function_exists( 'platejka_resolve_section_data' ) ? platejka_resolve_section_data( array( 'slug' => 'calculator', 'mode' => 'default', 'row' => array() ), (int) get_queried_object_id() ) : array();
$calculator_labels = platejka_section_label_map( $calculator_data['labels'] ?? array() );
$calculator_rates = function_exists( 'platejka_core_get_exchange_rates' ) ? platejka_core_get_exchange_rates() : array();
$hero_description = preg_replace( '/<p>/', '<p class="hero__subtitle" data-hero-copy>', wp_kses_post( $section_data['description'] ?? '' ) );
?>
<section class="hero" id="<?php echo esc_attr( $root_id ); ?>" data-hero>
  <div class="container"><div class="hero__layout"><div class="hero__content">
    <div class="hero__wrap hero__wrap_top" style="<?php echo $hero_image_url ? '--hero-image:url(\'' . esc_url( $hero_image_url ) . '\');' : ''; ?>--hero-blur:url('img/hero-blur.png');background:var(--surface-inverse)" data-hero-panel>
      <?php echo platejka_section_image( $section_data['image'] ?? 0, 'large', array( 'class' => 'hero__image', 'loading' => 'eager', 'fetchpriority' => 'high', 'sizes' => '(max-width: 767px) 100vw, 553px', 'data-hero-image' => '' ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?><span class="hero__blur" aria-hidden="true" data-hero-blur></span>
      <h1 class="hero__title" data-hero-copy><span class="hero__title-primary"><?php echo esc_html( $section_data['title'] ?? '' ); ?></span><?php if ( ! empty( $section_data['title_accent'] ) ) : ?><span class="hero__title-secondary"><?php echo esc_html( $section_data['title_accent'] ); ?></span><?php endif; ?></h1>
      <?php echo $hero_description; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
      <ul class="list-reset hero__items" data-hero-copy><?php foreach ( $items as $item ) : ?><li class="hero__item"><span class="hero__item-title"><?php echo esc_html( $item['title'] ?? '' ); ?></span><span class="hero__item-content"><?php echo wp_kses_post( $item['text'] ?? '' ); ?></span></li><?php endforeach; ?></ul><p class="hero__info" data-hero-copy><?php echo esc_html__( 'Полный пакет закрывающих документов для валютного контроля и таможни', 'platejka_rework' ); ?></p>
    </div>
    <ul class="list-reset hero__trust" data-hero-cards><?php foreach ( $trust as $index => $item ) : $trust_variant = array( 'experience', 'registry', 'association' )[ $index % 3 ]; ?><li class="hero__trust-card hero__trust-card_<?php echo esc_attr( $trust_variant ); ?>"><?php if ( 0 === $index ) : ?><div class="hero__trust-years" aria-label="<?php echo esc_attr( $item['value'] ?? '' ); ?>"><span aria-hidden="true"><?php echo esc_html( $item['value'] ?? '' ); ?></span></div><p class="hero__trust-caption"><?php echo esc_html( $item['title'] ?? '' ); ?></p><?php else : ?><p class="hero__trust-title"><?php echo esc_html( $item['title'] ?? '' ); ?></p><?php echo platejka_section_image( $item['image'] ?? 0, 'medium', array( 'class' => 'hero__trust-decor hero__trust-decor_' . $trust_variant, 'loading' => 'lazy', 'sizes' => '161px' ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?><?php if ( ! empty( $item['link']['url'] ) ) : ?><a class="ui-link <?php echo 1 === $index ? 'ui-link--overlay' : 'ui-link--inverse'; ?> hero__trust-link" href="<?php echo esc_url( $item['link']['url'] ); ?>"><?php echo esc_html( $item['link']['title'] ?? '' ); ?></a><?php endif; ?><?php endif; ?></li><?php endforeach; ?></ul>
  </div><form class="hero-calculator" data-hero-calculator data-currency-rates="<?php echo esc_attr( wp_json_encode( $calculator_rates ) ); ?>" novalidate><div class="hero-calculator__banner"><span><?php echo esc_html__( 'В реестре ЦБ РФ и СРО платёжных агентов', 'platejka_rework' ); ?></span></div><div class="hero-calculator__body"><h2 class="hero-calculator__title"><?php echo esc_html( $calculator_labels['summary'] ?? '' ); ?></h2><div class="ui-tabs hero-calculator__currencies" aria-label="<?php echo esc_attr( $calculator_labels['currency'] ?? '' ); ?>"><span class="hero-calculator__indicator" data-currency-indicator aria-hidden="true"></span><?php foreach ( array( 'CNY' => 'cn-flag.png', 'USD' => 'usa-flag.png' ) as $currency => $flag ) : ?><button class="ui-tab hero-calculator__currency<?php echo 'CNY' === $currency ? ' is-active' : ''; ?>" type="button" data-currency="<?php echo esc_attr( $currency ); ?>" aria-pressed="<?php echo 'CNY' === $currency ? 'true' : 'false'; ?>"><img class="hero-calculator__flag" src="img/<?php echo esc_attr( $flag ); ?>" width="20" height="20" alt=""><?php echo esc_html( $currency ); ?></button><?php endforeach; ?></div><div class="hero-calculator__field"><label class="hero-calculator__label" for="hero-amount"><?php echo esc_html( $calculator_labels['amount'] ?? '' ); ?></label><div class="hero-calculator__amount-wrap"><input class="ui-amount-input hero-calculator__amount" id="hero-amount" name="amount" type="number" min="1" step="1" inputmode="numeric" value="100000" data-role="amount" required><span class="hero-calculator__symbol" data-role="currency-symbol" aria-hidden="true">¥</span></div></div><dl class="hero-calculator__results"><?php foreach ( array( 'official_rate' => 'official-rate', 'conversion_rate' => 'conversion-rate', 'commission' => 'commission', 'total' => 'grand-total' ) as $label_key => $role ) : ?><div class="hero-calculator__result-row<?php echo 'total' === $label_key ? ' hero-calculator__result-row_total' : ''; ?>"><dt><?php echo esc_html( $calculator_labels[ $label_key ] ?? '' ); ?></dt><dd><output data-role="<?php echo esc_attr( $role ); ?>">0 ₽</output></dd></div><?php endforeach; ?></dl><button class="ui-button hero-calculator__submit" type="submit"><?php echo esc_html( $calculator_labels['request'] ?? '' ); ?></button><p class="hero-calculator__note"><?php echo esc_html( $calculator_data['note'] ?? '' ); ?></p></div></form></div></div>
  <dialog class="contact-dialog" data-contact-dialog aria-label="<?php echo esc_attr( $calculator_labels['dialog'] ?? '' ); ?>"><div class="contact-dialog__content"><button class="btn-reset contact-dialog__close" type="button" data-dialog-close aria-label="<?php echo esc_attr( $calculator_labels['close'] ?? '' ); ?>">×</button><h2 class="contact-dialog__title"><?php echo esc_html( $calculator_labels['dialog'] ?? '' ); ?></h2><p class="contact-dialog__text"><?php echo esc_html__( 'Параметры расчёта готовы для заявки.', 'platejka_rework' ); ?></p><p class="contact-dialog__summary" data-dialog-summary><?php echo esc_html( $calculator_labels['summary_empty'] ?? '' ); ?></p><div data-cf7-mount><?php echo platejka_cf7_form( $calculator_data['form'] ?? 0 ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></div></div></dialog>
</section>
<script type="application/json" data-calculator-labels-for="<?php echo esc_attr( $root_id ); ?>"><?php echo wp_json_encode( $calculator_labels ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></script>
