<?php
$root_id = $section_anchor ?: $section_instance; $title_id = platejka_section_dom_id( $section_instance, 'title' );
$rates = function_exists( 'platejka_core_get_exchange_rates' ) ? platejka_core_get_exchange_rates() : array();
$items = is_array( $section_data['items'] ?? null ) ? $section_data['items'] : array();
?>
<section class="calculator" id="<?php echo esc_attr( $root_id ); ?>" data-transfer-calculator-section aria-labelledby="<?php echo esc_attr( $title_id ); ?>"><div class="container">
  <header class="calculator__heading"><?php if ( ! empty( $section_data['eyebrow'] ) ) : ?><span class="calculator__badge"><?php echo esc_html( $section_data['eyebrow'] ); ?></span><?php endif; ?><h2 id="<?php echo esc_attr( $title_id ); ?>"><?php echo esc_html( $section_data['title'] ?? '' ); ?></h2><div><?php echo wp_kses_post( $section_data['description'] ?? '' ); ?></div></header>
  <form class="calculator__panel" data-transfer-calculator data-currency-rates="<?php echo esc_attr( wp_json_encode( $rates ) ); ?>" novalidate><div class="calculator__columns"><div class="calculator__fields">
    <div class="ui-tabs calculator__currencies" role="group" aria-label="<?php echo esc_attr__( 'Валюта платежа', 'platejka_rework' ); ?>"><span class="calculator__indicator" data-currency-indicator aria-hidden="true"></span><?php foreach ( array( 'CNY' => 'cn-flag.png', 'USD' => 'usa-flag.png', 'EUR' => 'eur-flag.png' ) as $currency => $flag ) : ?><button class="ui-tab calculator__currency<?php echo 'CNY' === $currency ? ' is-active' : ''; ?>" type="button" data-currency="<?php echo esc_attr( $currency ); ?>" aria-pressed="<?php echo 'CNY' === $currency ? 'true' : 'false'; ?>"><img src="img/<?php echo esc_attr( $flag ); ?>" width="20" height="20" alt=""> <?php echo esc_html( $currency ); ?></button><?php endforeach; ?></div>
    <div class="calculator__route"><label class="calculator__field"><span class="calculator__field-label"><?php echo esc_html__( 'Страна Отправитель', 'platejka_rework' ); ?></span><select name="country_from" data-role="country-from"><option value="RU"><?php echo esc_html__( 'Россия', 'platejka_rework' ); ?></option></select></label><label class="calculator__field"><span class="calculator__field-label"><?php echo esc_html__( 'Страна Получатель', 'platejka_rework' ); ?></span><select name="country_to" data-role="country-to"><option value="CN"><?php echo esc_html__( 'Китай', 'platejka_rework' ); ?></option><option value="TR"><?php echo esc_html__( 'Турция', 'platejka_rework' ); ?></option><option value="US"><?php echo esc_html__( 'США', 'platejka_rework' ); ?></option></select></label></div>
    <label class="calculator__field calculator__amount-field"><span class="calculator__field-label"><?php echo esc_html__( 'Сумма:', 'platejka_rework' ); ?></span><span class="calculator__amount-wrap"><input name="amount" type="text" inputmode="decimal" autocomplete="off" value="100 000" data-role="amount" required><span data-role="currency-symbol" aria-hidden="true">¥</span></span></label>
    <?php if ( ! empty( $section_data['note'] ) ) : ?><p class="calculator__rate-note"><?php echo esc_html( $section_data['note'] ); ?></p><?php endif; ?>
    <div class="calculator__benefits"><?php foreach ( $items as $item ) : ?><article><h3><?php echo esc_html( $item['title'] ?? '' ); ?></h3><div><?php echo wp_kses_post( $item['text'] ?? '' ); ?></div></article><?php endforeach; ?></div>
  </div><div class="calculator__summary"><h3><?php echo esc_html__( 'Предварительный расчёт', 'platejka_rework' ); ?></h3><dl class="calculator__results"><div><dt><?php echo esc_html__( 'Официальный курс', 'platejka_rework' ); ?></dt><dd><output data-role="official-rate">0 ₽</output></dd></div><div><dt><?php echo esc_html__( 'Наш курс конвертации', 'platejka_rework' ); ?></dt><dd><output data-role="conversion-rate">0 ₽</output></dd></div><div><dt><?php echo esc_html__( 'Комиссия агента', 'platejka_rework' ); ?></dt><dd><output data-role="commission">0 ₽</output></dd></div><div class="calculator__total"><dt><?php echo esc_html__( 'Итого в рублях', 'platejka_rework' ); ?></dt><dd><output data-role="grand-total">0 ₽</output></dd></div></dl><div class="calculator__actions"><button class="ui-button" type="submit" data-action="request"><?php echo esc_html__( 'Отправить заявку', 'platejka_rework' ); ?></button><button class="ui-button calculator__telegram" type="button" data-action="telegram"><?php echo esc_html__( 'Написать', 'platejka_rework' ); ?></button></div><p class="calculator__contract-note"><?php echo esc_html( $section_data['note'] ?? '' ); ?></p></div></div></form>
</div><dialog class="contact-dialog" data-contact-dialog aria-label="<?php echo esc_attr__( 'Оставить заявку', 'platejka_rework' ); ?>"><div class="contact-dialog__content"><button class="btn-reset contact-dialog__close" type="button" data-dialog-close aria-label="<?php echo esc_attr__( 'Закрыть окно', 'platejka_rework' ); ?>">×</button><p class="contact-dialog__summary" data-dialog-summary></p><div data-cf7-mount><?php echo platejka_cf7_form( $section_data['form'] ?? 0 ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></div></div></dialog></section>
