<?php
$root_id        = $section_anchor ?: $section_instance;
$title_id       = platejka_section_dom_id( $section_instance, 'title' );
$video_panel_id = platejka_section_dom_id( $section_instance, 'video-panel' );
$video_tab_id   = platejka_section_dom_id( $section_instance, 'video-tab' );
$text_panel_id  = platejka_section_dom_id( $section_instance, 'text-panel' );
$text_tab_id    = platejka_section_dom_id( $section_instance, 'text-tab' );
$dialog_id      = platejka_section_dom_id( $section_instance, 'dialog-title' );
$items          = is_array( $section_data['items'] ?? null ) ? $section_data['items'] : array();
$video_items    = is_array( $section_data['video_items'] ?? null ) ? $section_data['video_items'] : array();
$ratings        = is_array( $section_data['ratings'] ?? null ) ? $section_data['ratings'] : array();
$labels         = platejka_section_label_map( $section_data['labels'] ?? array() );
?>
<section class="review-main" id="<?php echo esc_attr( $root_id ); ?>" data-review aria-labelledby="<?php echo esc_attr( $title_id ); ?>">
  <div class="container"><header class="review-main__header"><div class="review-main__heading">
    <?php if ( ! empty( $section_data['eyebrow'] ) ) : ?><p class="review-main__eyebrow"><?php echo esc_html( $section_data['eyebrow'] ); ?></p><?php endif; ?>
    <h2 id="<?php echo esc_attr( $title_id ); ?>"><?php echo esc_html( $section_data['title'] ?? '' ); ?></h2><div class="review-main__lead"><span class="review-main__lead-desktop"><?php echo wp_kses_post( $section_data['description'] ?? '' ); ?></span><span class="review-main__lead-tablet"><?php echo esc_html( $labels['tablet_lead'] ?? '' ); ?></span></div>
  </div><div class="review-main__summary"><div class="review-main__tabs" role="tablist" aria-label="<?php echo esc_attr( $labels['tabs_label'] ?? '' ); ?>" data-review-tabs><button type="button" role="tab" id="<?php echo esc_attr( $video_tab_id ); ?>" aria-controls="<?php echo esc_attr( $video_panel_id ); ?>" aria-selected="true"><?php echo esc_html( $labels['video_tab'] ?? '' ); ?></button><button type="button" role="tab" id="<?php echo esc_attr( $text_tab_id ); ?>" aria-controls="<?php echo esc_attr( $text_panel_id ); ?>" aria-selected="false" tabindex="-1"><?php echo esc_html( $labels['text_tab'] ?? '' ); ?></button></div><ul class="list-reset review-main__ratings" aria-label="<?php echo esc_attr( $labels['ratings_label'] ?? $labels['tabs_label'] ?? '' ); ?>"><?php foreach ( $ratings as $index => $rating ) : ?><li class="review-main__rating<?php echo 0 === $index ? ' review-main__rating--accent' : ''; ?>"><div><strong><?php echo esc_html( $rating['value'] ?? '' ); ?></strong><?php echo platejka_section_image( $rating['image'] ?? 0, 'thumbnail', array( 'loading' => 'lazy', 'sizes' => '72px', 'alt' => $rating['title'] ?? '' ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></div><div><span aria-label="<?php echo esc_attr( sprintf( '%s: %s', $rating['title'] ?? '', $rating['value'] ?? '' ) ); ?>">★★★★★</span><small><?php echo esc_html( $rating['caption'] ?? '' ); ?></small></div></li><?php endforeach; ?></ul></div></header>
  <div id="<?php echo esc_attr( $video_panel_id ); ?>" role="tabpanel" aria-labelledby="<?php echo esc_attr( $video_tab_id ); ?>" data-review-video-panel><div class="review-main__slider" data-horizontal-slider data-horizontal-slider-min-controls="6"><div class="review-main__viewport" data-horizontal-slider-viewport tabindex="0" role="region" aria-label="<?php echo esc_attr( $labels['video_region'] ?? '' ); ?>"><div class="review-main__track" data-horizontal-slider-track>
    <?php foreach ( $video_items as $item ) : $poster_url = is_numeric( $item['image'] ?? null ) ? wp_get_attachment_image_url( (int) $item['image'], 'large' ) : ''; ?><article class="review-main__video-card" data-horizontal-slider-slide<?php echo $poster_url ? ' style="--review-image:url(\'' . esc_url( $poster_url ) . '\')"' : ''; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>><?php echo platejka_section_image( $item['image'] ?? 0, 'large', array( 'class' => 'review-main__video-card-image', 'loading' => 'lazy', 'sizes' => '(max-width: 767px) 100vw, 416px', 'style' => 'position:absolute;z-index:0;inset:0;width:100%;height:100%;object-fit:cover' ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?><span aria-hidden="true" style="position:absolute;z-index:1;inset:35% 0 0;background:linear-gradient(transparent,rgba(0,0,0,.88))"></span><div style="z-index:2"><h3><?php echo esc_html( $item['title'] ?? '' ); ?></h3><p><?php echo wp_kses_post( $item['text'] ?? '' ); ?></p><button type="button" data-review-video="<?php echo esc_url( platejka_section_file_url( $item['file'] ?? 0 ) ); ?>"><?php echo esc_html( $labels['watch'] ?? '' ); ?></button></div></article><?php endforeach; ?>
  </div></div><div class="review-main__controls" data-horizontal-slider-controls><button type="button" data-horizontal-slider-prev aria-label="<?php echo esc_attr( $labels['prev_video'] ?? $labels['video_tab'] ?? '' ); ?>">‹</button><button type="button" data-horizontal-slider-next aria-label="<?php echo esc_attr( $labels['next_video'] ?? $labels['video_tab'] ?? '' ); ?>">›</button></div></div></div>
  <div id="<?php echo esc_attr( $text_panel_id ); ?>" role="tabpanel" aria-labelledby="<?php echo esc_attr( $text_tab_id ); ?>" data-review-text-panel hidden><div class="review-main__slider review-main__text-slider" data-horizontal-slider data-horizontal-slider-min-controls="4"><div class="review-main__viewport" data-horizontal-slider-viewport tabindex="0" role="region" aria-label="<?php echo esc_attr( $labels['text_region'] ?? '' ); ?>"><div class="review-main__track review-main__text-track" data-horizontal-slider-track>
    <?php foreach ( $items as $item ) : $review_date = ! empty( $item['date'] ) ? strtotime( (string) $item['date'] ) : false; ?><article class="review-main__text-card" data-horizontal-slider-slide><div class="review-main__stars" aria-label="<?php echo esc_attr( $item['value'] ?? '' ); ?>"><?php echo esc_html( $item['value'] ?? '' ); ?></div><blockquote><?php echo wp_kses_post( $item['text'] ?? '' ); ?></blockquote><span class="review-main__source"><?php echo platejka_section_image( $item['image'] ?? 0, 'thumbnail', array( 'loading' => 'lazy', 'sizes' => '20px' ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?><?php echo esc_html( $item['caption'] ?? '' ); ?></span><footer><strong><?php echo esc_html( $item['title'] ?? '' ); ?></strong><?php if ( $review_date ) : ?><time datetime="<?php echo esc_attr( gmdate( 'Y-m-d', $review_date ) ); ?>"><?php echo esc_html( wp_date( 'd.m.Y', $review_date ) ); ?></time><?php endif; ?></footer></article><?php endforeach; ?>
  </div></div><div class="review-main__controls" data-horizontal-slider-controls hidden><button type="button" data-horizontal-slider-prev aria-label="<?php echo esc_attr( $labels['prev_text'] ?? $labels['text_tab'] ?? '' ); ?>">‹</button><button type="button" data-horizontal-slider-next aria-label="<?php echo esc_attr( $labels['next_text'] ?? $labels['text_tab'] ?? '' ); ?>">›</button></div></div></div></div>
  <dialog class="review-main__dialog" data-review-dialog aria-labelledby="<?php echo esc_attr( $dialog_id ); ?>"><button class="review-main__close" type="button" data-review-close aria-label="<?php echo esc_attr( $labels['close'] ?? '' ); ?>">×</button><div class="review-main__dialog-card"><video preload="none" playsinline></video><div class="review-main__loading" data-review-loading role="status" aria-label="<?php echo esc_attr( $labels['loading'] ?? '' ); ?>" hidden></div><div class="review-main__dialog-caption"><h2 id="<?php echo esc_attr( $dialog_id ); ?>"></h2><p class="review-main__dialog-role" data-review-dialog-role></p><p class="review-main__video-empty" data-review-empty><?php echo esc_html( $labels['empty'] ?? '' ); ?></p><p class="review-main__video-error review-video-error" data-review-error hidden><?php echo esc_html( $labels['error'] ?? '' ); ?></p></div></div></dialog>
</section>
